module.exports = {
  apps: [
    {
      name: 'vms-recorder',
      script: '/home/camera/app/vms/services/recorder/build/vms-recorder',
      cwd: '/home/camera/app/vms/services/recorder/build',
      interpreter: 'none',
      env: {
        DATABASE_HOST: 'localhost',
        DATABASE_PORT: '5432',
        DATABASE_NAME: 'vms',
        DATABASE_USER: 'vms_user',
        POSTGRES_PASSWORD: 'l3Gd63G2iBlqtiWI',
        REDIS_HOST: 'localhost',
        REDIS_PORT: '6379',
        RECORDING_PATH: '/home/camera/app/vms/data/recordings',
        QSV_DEVICE: '/dev/dri/renderD128',
        QSV_LOW_QUALITY: '720p',
        QSV_HIGH_QUALITY: '1440p',
        RETENTION_DAYS: '2',
        MIN_FREE_SPACE_GB: '10',
        CLEANUP_INTERVAL_HOURS: '1',
        MAX_RETRIES: '10',
        RETRY_DELAY_SECONDS: '5',
        // MediaMTX health check settings
        MEDIAMTX_API_URL: 'http://localhost:9997',
        MEDIAMTX_HEALTH_CHECK_INTERVAL: '30'
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      watch: false,
      max_memory_restart: '8G',
      error_file: '/home/camera/app/vms/logs/recorder-error.log',
      out_file: '/home/camera/app/vms/logs/recorder-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      kill_timeout: 10000
    },
    {
      name: 'vms-mediamtx',
      script: '/home/camera/app/vms/services/streaming/start-mediamtx.sh',
      cwd: '/home/camera/app/vms/services/streaming',
      interpreter: 'bash',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 3000,
      watch: false,
      error_file: '/home/camera/app/vms/logs/mediamtx-error.log',
      out_file: '/home/camera/app/vms/logs/mediamtx-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      kill_timeout: 5000
    },
    {
      name: 'vms-api',
      script: '/home/camera/app/vms/services/api/dist/main.js',
      cwd: '/home/camera/app/vms/services/api',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        DATABASE_HOST: 'localhost',
        DATABASE_PORT: '5432',
        DATABASE_NAME: 'vms',
        DATABASE_USER: 'vms_user',
        POSTGRES_PASSWORD: 'l3Gd63G2iBlqtiWI',
        DATABASE_URL: 'postgresql://vms_user:l3Gd63G2iBlqtiWI@localhost:5432/vms',
        REDIS_HOST: 'localhost',
        REDIS_PORT: '6379',
        JWT_SECRET: 'change_this_to_random_64_char_string_in_production',
        CORS_ORIGIN: 'http://localhost:8080'
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 3000,
      watch: false,
      max_memory_restart: '1G',
      error_file: '/home/camera/app/vms/logs/api-error.log',
      out_file: '/home/camera/app/vms/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      kill_timeout: 5000
    }
  ]
};
